services:
  database:
    image: mysql:8.0
    container_name: service_desk_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_desk
    ports:
      - "3306:3306"

  php:
    build: .
    container_name: service_desk_php
    environment:
      - GIT_CONFIG_PARAMETERS='safe.directory=/var/www/html'
    volumes:
      - .:/var/www/html
      - php_var:/var/www/html/var
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: service_desk_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: service_desk_pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database

volumes:
  php_var: