name: Symfony Tests
on: [push, pull_request]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    
    env:
      APP_ENV: test
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/app_test.db"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, pdo_sqlite, intl
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create Database and Schema
        run: |
          mkdir -p var
          php bin/console doctrine:schema:create --env=test

      - name: Run Tests
        run: php bin/phpunit
